name: tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    name: Run tests
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install system packages (macos-latest)
      if: matrix.runs-on == 'macos-latest'
      run: brew install swig
    - name: Install system packages (ubuntu-latest)
      if: matrix.runs-on == 'ubuntu-latest'
      run: sudo apt-get install swig
    - name: Install python packages
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install -r requirements.txt
        python -m pip install -r requirements.dev.txt
        python -m pip install .
    - name: Lint with flake8
      run: |
        python -m pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        python -m flake8 coax --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings.
        python -m flake8 coax --count --exit-zero --max-complexity=10 --statistics
    - name: Test with pytest
      run: |
        python -m pip install pytest pytest-cov
        python -m pytest --cov=coax --cov-report=xml coax -v
